### ISSUE TITLE
Unable to resolve module 'expo'

### ISSUE THREAD

**Issue by hmenzagh** [tomzaku/react-native-shimmer-placeholder#10]
This code is throwing an error on `require( 'expo' ).LinearGradient` even if `module_exist` returns false (I don't have expo) .. I tried to fix this and do a PR but with no success ..

```js
// https://gist.github.com/FGRibreau/3135914
function module_exist(name){
  try{require(name);} catch(err){if(err.code === 'MODULE_NOT_FOUND'){return false;}}
  return true;
};

const LinearGradient = module_exist( 'expo' ) ? require( 'expo' ).LinearGradient : require( 'react-native-linear-gradient' )
```

I will do a temporary fix for the moment !

**Comment by tomzaku** [comment]
I tried many way but no success with this. 
Any one help me?

**Comment by tomzaku** [comment]
Fixed!
https://github.com/tomzaku/react-native-shimmer-placeholder/commit/c800a28d0afabc01e737a28d917e8bb2f3906b6e

**Comment by hmenzagh** [comment]
If I get some spare time i'll take a stronger look at this !
