### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jr-k** [tomzaku/react-native-shimmer-placeholder#13]
Hi,

I noticed that when I run my app with this library the memory consumption increase over time until app crashes. This happens only when autoRun = true

Any idea ?

**Comment by tomzaku** [comment]
Hey @jr-k  [check it out](https://github.com/tomzaku/react-native-shimmer-placeholder/commit/6f5b20d709df96964df8b6af6d444d3272ea6516),
Using usenativedriver right now.
Cheer,

**Comment by jr-k** [comment]
Yep ! Awesome, thanks.
