### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by anhtuank7c** [tomzaku/react-native-shimmer-placeholder#2]
I tried to add autoRun to Shimmer, but it drop so much js frame.

Two picture compare autoRun is true and false

autoRun = true
![screen shot 2017-06-20 at 10 06 31 am](https://user-images.githubusercontent.com/3163410/27314823-62e65352-55a0-11e7-923f-5cbb48e357c5.png)

autoRun = false
![screen shot 2017-06-20 at 10 06 58 am](https://user-images.githubusercontent.com/3163410/27314822-62e4e832-55a0-11e7-9e72-be19f4bcbea5.png)

**Comment by tomzaku** [comment]
Could I see your code, plz?
@anhtuank7c
