### ISSUE TITLE
Prepare next version

### ISSUE THREAD

**Issue by tomzaku** [tomzaku/react-native-shimmer-placeholder#20]
+ [x] Add type for typescript
+ [ ] Add component for parallel animation
+ [ ] Add component for sequence animation
+ [x] Add more styles
+ [x] Convert to hooks

**Comment by eddyoc** [comment]
Also support for Expo SDK 33+ would be champion

**Comment by tomzaku** [comment]
I need your help. I don't have time to maintain this package, please raise your PR, I will take a look

**Comment by luizjr** [comment]
Are you still going to continue?
This package is very good, so is the proposal!

Because we didn't upload a documentation for it, and we updated the package to the latest React Native SDK ...

It is very important for me to keep EXPO support

**Comment by tomzaku** [comment]
- [x] Supported EXPO by default
- [x] Converted to hook
- [x] Updated type for typescript
