### ISSUE TITLE
[iOS] Shimmer does not reset back to the start position

### ISSUE THREAD

**Issue by schahriar** [tomzaku/react-native-shimmer-placeholder#3]
![bug](https://user-images.githubusercontent.com/6145207/30196426-7e30d07a-9415-11e7-8ef9-96506ef65f53.gif)
I'm seeing this odd issue where an autorun shimmer is not resetting to the start position after the first round.

The setup is pretty basic with the exception of linear-gradient being linked manually in Xcode:
```javascript
<View>
  <ShimmerPlaceHolder
    style={{ width: 100 }}
    duration={1000}
    autoRun={true}/>
  <ShimmerPlaceHolder
    style={{ width: 100 }}
    duration={2000}
    autoRun={true}/>
</View>
```

and these are running against RN (0.48.1) and React Fiber (16.0.0-alpha.12) with `react-native-linear-gradient` version 2.3.0 and version 1.0.13 of this module running on iOS simulator (iPhone 7, iOS 10.3)

I would appreciate it if you can look into this to see if it is reproducible.

**Comment by tomzaku** [comment]
Hello @schahriar,
Thanks for your issue.
I've already fixed loop and also updated example. [Check it out](https://github.com/tomzaku/react-native-shimmer-placeholder/commit/a0f6a1f4f5f24960ed5bf7a71fd4cc6e679bf8a3)
Check to update [1.0.14](https://github.com/tomzaku/react-native-shimmer-placeholder/tree/v1.0.14)
If your problem also happen, make sure remove node_modules by command
`rm -rf node_modules`
And install package again by this
`yarn` or `npm install`
