### ISSUE TITLE
Make shimmer smoother

### ISSUE THREAD

**Issue by dkwl93** [tomzaku/react-native-shimmer-placeholder#37]
Hi there, The package is working great so thanks for all your hard work. However, I noticed that the "shimmer" was quite rough. Is there anyway to make this look smoother?

Thanks

Dan

**Comment by tomzaku** [comment]
Could you share me your code.
Because I make sure that I tested a lot about performance

**Comment by dkwl93** [comment]
Performance is fine, I was thinking more about the gradient of the shimmer. 

Attached is a screenshot of what I mean

![image](https://user-images.githubusercontent.com/21037732/70297292-cde42800-1830-11ea-878c-31461845b32e.png)
@tomzaku

**Comment by tomzaku** [comment]
You can use these props to make it smooth
`widthShimmer`, `colorShimmer`
Try to add widthShimmer longer than default

**Comment by dkwl93** [comment]
![shimmer](https://user-images.githubusercontent.com/21037732/70593457-8985cd00-1c20-11ea-875c-840391c7412b.gif)
Made it wider. Now it seems like it ends too soon?

**Comment by dkwl93** [comment]
It looks like it starts with the "shimmer" part already in the view. I'm expecting it to come into the view from outside. Hope this makes sense

**Comment by tomzaku** [comment]
Could I see your code. The shimmer actually outside of the view

From source code:
```
 let outputRange = [-width, width];
    if (reverse) {
      outputRange = outputRange.reverse();
    }
    const linearTranslate = this.state.beginShimmerPosition.interpolate({
      inputRange: [-1, 1],
      outputRange: outputRange
    });
```
So you can see the outputRange begin with "-width", that means `left = -width`

**Comment by dkwl93** [comment]
@tomzaku I know what the problem is. Instead of passing in a width/height via props like
```
<ShimmerPlaceholder width={x} height={y} />
```

I'm passing it in via 
```
<ShimmerPlaceholder style={{ width: x, height: y }} />
```

The outputRange only uses width from prop, *not* from styles. I can create a PR to fix this if you want

**Comment by tomzaku** [comment]
Great. Could you create the PR for me
