### ISSUE TITLE
Image does not load

### ISSUE THREAD

**Issue by borasumer** [tomzaku/react-native-shimmer-placeholder#40]
When you wrap an image with ShimmerPlaceholder, image does not load so you cannot use image's onLoad prop. I don't know what is wrong.

**Comment by tomzaku** [comment]
Can you check again with new version?

**Comment by M1ST4KE** [comment]
I have shimmer placeholder version `2.0.6` and react-native `0.62.2`, in function components images still doesn't load.

**Comment by tomzaku** [comment]
@M1ST4KE Can you provide me the source code?

**Comment by tomzaku** [comment]
```
   <ShimmerPlaceholder
        width={150}
        height={150}
        shimmerStyle={{ borderRadius: 100 }}
        visible={avatarVisible}
      >
        <Image
          style={{ width: 150, height: 150, borderRadius: 100 }}
          source={{ uri: 'https://unsplash.it/1000/1000' }}
          onLoadEnd={() => setAvatarVisible(true)}
        />
      </ShimmerPlaceholder>
```
https://github.com/tomzaku/react-native-shimmer-placeholder/blob/master/example/App.js
This works fine for me

**Comment by M1ST4KE** [comment]
Ok, it your code works, but when I remove `width` style property and set `flex: 1` in `Image` it the image doesn't work.

**Comment by tomzaku** [comment]
> Ok, it your code works, but when I remove `width` style property and set `flex: 1` in `Image` it the image doesn't work.

How about the height?
Can you show me the code?

**Comment by M1ST4KE** [comment]
iOS doesn't render images with size 0 so to be able not to set width or height in image, you have to set the min values. e.g.
This code will not work:
```
<ShimmerPlaceholder
        width={150}
        height={150}
        shimmerStyle={{ borderRadius: 100 }}
        visible={avatarVisible}
      >
        <Image
          style={{ width: 150, borderRadius: 100 }}
          source={{ uri: 'https://unsplash.it/1000/1000' }}
          onLoadEnd={() => setAvatarVisible(true)}
        />
      </ShimmerPlaceholder>
```
but this will work:
```
<ShimmerPlaceholder
        width={150}
        height={150}
        shimmerStyle={{ borderRadius: 100 }}
        visible={avatarVisible}
      >
        <Image
          style={{ width: 150, minHeight: 1, borderRadius: 100 }}
          source={{ uri: 'https://unsplash.it/1000/1000' }}
          onLoadEnd={() => setAvatarVisible(true)}
        />
      </ShimmerPlaceholder>
```

**Comment by tomzaku** [comment]
Hi @M1ST4KE,

The height is required in `Image` for both iOS and Android.

It will not render without height and not related to ShimmerPlaceholder.

For example: if you run those lines of code, Both Ios and Android won't show Image whether you use ShimmerPlaceholder 
```
 <Image
        style={{ width: 150, borderRadius: 100 }}
        source={{ uri: 'https://unsplash.it/1000/1000' }}
      />
```
