### ISSUE TITLE
It's possible reset animation?

### ISSUE THREAD

**Issue by jonathanmachado** [tomzaku/react-native-shimmer-placeholder#41]
Hi I need reset animation with action, this it's possible? I try to change state visible but don't have success.

Thanks

**Comment by jonathanmachado** [comment]
Hi I fix in this [https://github.com/tomzaku/react-native-shimmer-placeholder/pull/42](PR) please check thanks.

**Comment by tomzaku** [comment]
Yes can. You can use ref to get `getAnimated` of ShimmerPlaceholder component.
