### ISSUE TITLE
Make gradient component injectable

### ISSUE THREAD

**Issue by brentvatne** [tomzaku/react-native-shimmer-placeholder#44]
It would be useful to be able to provide the gradient component similar to how redux-persist asks you to pass in the storage API: https://github.com/rt2zz/redux-persist#v6-upgrade

**Comment by tomzaku** [comment]
Good idea. Do you have any plans to create a PR for me?

**Comment by brentvatne** [comment]
i'm not planning on it but it'd be cool to see :)

another thing that could be done to make this work out of the box in managed expo projects is to do something like this pr https://github.com/react-native-community/async-storage/pull/368 - use .expo.js extension to use expo-linear-gradient rather than react-native-linear-gradient when in expo managed apps

**Comment by tomzaku** [comment]
Now we're using : 
```js
import { createShimmerPlaceholder } from 'react-native-shimmer-placeholder'

const ShimmerPlaceholder = createShimmerPlaceholder(LinearGradient)
...
<ShimmerPlaceholder />

```
or
```js
import ShimmerPlaceholder from 'react-native-shimmer-placeholder'

<ShimmerPlaceholder
LinearGradient={LinearGradient}
/>
```

**Comment by brentvatne** [comment]
nice one!

**Comment by tomzaku** [comment]
For expo user.
No longer imported `LinearGradient`. It will be added by default

For example
```
import ShimmerPlaceholder from 'react-native-shimmer-placeholder'
<ShimmerPlaceholder />
```
