### ISSUE TITLE
Image is not hidden when visible={false}

### ISSUE THREAD

**Issue by M-i-k-e-l** [tomzaku/react-native-shimmer-placeholder#50]
Steps to reproduce:
1. react-native init shimmer
2. npm i react-native-linear-gradient --save
3. npm i react-native-shimmer-placeholder --save
4. pod install

Change `App.js` to [this](https://gist.github.com/M-i-k-e-l/98fd3945642565a62fdcccc09bc3470b).

The bug: as seen in the attached video, the images are shown while the placeholder is shown.
Expected: the images will be shown only when `visible={true}`

[Image shown video.zip](https://github.com/tomzaku/react-native-shimmer-placeholder/files/5049918/Image.shown.video.zip)

**Comment by tomzaku** [comment]
Can you test again? It has been fixed
