### ISSUE TITLE
NSMutableDictionary cannot be converted to a YGValue

### ISSUE THREAD

**Issue by vishgoel007** [tomzaku/react-native-shimmer-placeholder#52]
When i updated the package to its latest version starts encountering below error
``` 
JSON value '{x = 2; y = “0.5"; }' of type NSMutableDicitionary cannot be converetd to a YG Value
```
But looks like changing the start and end with startPoint and endPoint respectively in below code(in ShimmerPlaceholder.js) fixed the issue.

```
<LinearGradient
          colors={shimmerColors}
          style={{ flex: 1, width: width * shimmerWidthPercent }}
          start={{
            x: -1,
            y: 0.5,
          }}
          end={{
            x: 2,
            y: 0.5,
          }}
          locations={location}
        />
```

Update : After renaming the props it stopped animating.

**Comment by tomzaku** [comment]
Hi @vishgoel007 , Since the [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) has been upgraded, so the API has been changed. So you can take a look of that docs.

**Comment by tomzaku** [comment]
If you still have problems, can u send me the environment?
Are you using exp or  react-native-linear-gradient?
Which version are you using?
