### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by gurtejsmartdata** [tomzaku/react-native-shimmer-placeholder#53]
I have  installed the plugin in my project having react version 0.63.

I was trying to working  with this and writ following code. But app crashes each time.
import ShimmerPlaceHolder from 'react-native-shimmer-placeholder'

   <ShimmerPlaceHolder>
             <Text>Testing</Text>
   </ShimmerPlaceHolder> 

Anything wrong i am doing? Please update.

**Comment by tomzaku** [comment]
Are you using expo? If not, you need to install `react-native-linear-gradient` 

https://github.com/react-native-linear-gradient/react-native-linear-gradient

**Comment by tomzaku** [comment]
Duplicated thread.
Please follow [#54](https://github.com/tomzaku/react-native-shimmer-placeholder/issues/54)
