### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by priyak-sdei** [tomzaku/react-native-shimmer-placeholder#54]
We are using 
**React Version: 0.63**
**Wix React Navigation**
But app always gets crashed when we use the plugin.

**Below is the crash log generated**

>    java.lang.IllegalStateException: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 407
     detail: View tag:409
      children(0): [
     ],
      viewsToAdd(1): [
    [0,407],
     ],

**Code Wrote**

```
import` ShimmerPlaceHolder from 'react-native-shimmer-placeholder'
<ShimmerPlaceHolder>
                <Text>Hiii</Text>
  </ShimmerPlaceHolder>
```   

**Complete Crash Log**
```
 --------- beginning of crash
2020-10-16 18:24:41.048 16474-16474/com.truedriver E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.truedriver, PID: 16474
    java.lang.IllegalStateException: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 407
     detail: View tag:409
      children(0): [
     ],
      viewsToAdd(1): [
    [0,407],
     ],
    
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:390)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 407
     detail: View tag:409
      children(0): [
     ],
      viewsToAdd(1): [
    [0,407],
     ],
```

**Comment by tomzaku** [comment]
Are you using expo? If not, you need to install `react-native-linear-gradient` 

https://github.com/react-native-linear-gradient/react-native-linear-gradient

**Comment by jesse-savary** [comment]
@tomzaku Can confirm that our app is also producing this error, even with `react-native-linear-gradient` installed

**Comment by tomzaku** [comment]
@jesse-savary  Have you link react-native-linear-gradient in your package?
Can you run react-native-linear-gradient alone?

```
import LinearGradient from 'react-native-linear-gradient';

// Within your render function
<LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={styles.linearGradient}>
  <Text style={styles.buttonText}>
    Sign in with Facebook
  </Text>
</LinearGradient>

// Later on in your styles..
var styles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5
  },
  buttonText: {
    fontSize: 18,
    fontFamily: 'Gill Sans',
    textAlign: 'center',
    margin: 10,
    color: '#ffffff',
    backgroundColor: 'transparent',
  },
});

```

**Comment by jesse-savary** [comment]
@tomzaku Yes we can use the gradients alone. I managed to get the shimmer placeholders working by using the decorator function; passing in LinearGradient as a prop did not work and still caused a crash.

**Comment by tomzaku** [comment]
![image](https://user-images.githubusercontent.com/19413272/98429922-aa7ec880-20e4-11eb-9e28-8a02eed939fc.png)

I've just tested it on my machine, and it works fine now.
Can you confirm what is the difference between our flow?
```
npx react-native init reactNativeShimmer
cd reactNativeShimmer
yarn add react-native-linear-gradient
npx pod-install
yarn add react-native-shimmer-placeholder
yarn ios
```

And my code
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import LinearGradient from 'react-native-linear-gradient';
import { createShimmerPlaceholder } from 'react-native-shimmer-placeholder'

const ShimmerPlaceHolder = createShimmerPlaceholder(LinearGradient)

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ShimmerPlaceHolder />
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({

});

export default App;

```

package.json
```
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-shimmer-placeholder": "^2.0.6"
  },
```

**Comment by priyak-sdei** [comment]
> ![image](https://user-images.githubusercontent.com/19413272/98429922-aa7ec880-20e4-11eb-9e28-8a02eed939fc.png)
> 
> I've just tested it on my machine, and it works fine now.
> Can you confirm what is the difference between our flow?
> 
> ```
> npx react-native init reactNativeShimmer
> cd reactNativeShimmer
> yarn add react-native-linear-gradient
> npx pod-install
> yarn add react-native-shimmer-placeholder
> yarn ios
> ```
> 
> And my code
> 
> ```
> /**
>  * Sample React Native App
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  * @flow strict-local
>  */
> 
> import React from 'react';
> import {
>   SafeAreaView,
>   StyleSheet,
>   ScrollView,
>   View,
>   Text,
>   StatusBar,
> } from 'react-native';
> 
> import {
>   Header,
>   LearnMoreLinks,
>   Colors,
>   DebugInstructions,
>   ReloadInstructions,
> } from 'react-native/Libraries/NewAppScreen';
> import LinearGradient from 'react-native-linear-gradient';
> import { createShimmerPlaceholder } from 'react-native-shimmer-placeholder'
> 
> const ShimmerPlaceHolder = createShimmerPlaceholder(LinearGradient)
> 
> const App: () => React$Node = () => {
>   return (
>     <>
>       <StatusBar barStyle="dark-content" />
>       <SafeAreaView>
>         <ShimmerPlaceHolder />
>       </SafeAreaView>
>     </>
>   );
> };
> 
> const styles = StyleSheet.create({
> 
> });
> 
> export default App;
> ```
> 
> package.json
> 
> ```
> "dependencies": {
>     "react": "16.13.1",
>     "react-native": "0.63.3",
>     "react-native-linear-gradient": "^2.5.6",
>     "react-native-shimmer-placeholder": "^2.0.6"
>   },
> ```

Thanks, this code helps me. I was missing some thing. Issue solve now.
