### ISSUE TITLE
Expo 40 changes global variables

### ISSUE THREAD

**Issue by xmflsct** [tomzaku/react-native-shimmer-placeholder#55]
```
Your project is accessing the following APIs from a deprecated global rather than a module import: LinearGradient (expo-linear-gradient).

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals
```

**Comment by xmflsct** [comment]
https://github.com/expo/fyi/blob/master/deprecated-globals.md

**Comment by tomzaku** [comment]
So instead of using "global.Expo.LinearGradient", should use "global. __expo.LinearGradient"?

**Comment by xmflsct** [comment]
Reading the doc above, it seems like we need to add a dependency for `import Constants from 'expo-constants'`

**Comment by tomzaku** [comment]
Seem like it is not a good approach to import expo directly to my lib.
Maybe you can use this or ignore the warning.
```js
import LinearGradient from 'react-native-linear-gradient';
import { LinearGradient } from 'expo-linear-gradient';

const ShimmerPlaceHolder = createShimmerPlaceholder(LinearGradient)

...

<ShimmerPlaceHolder />
```

**Comment by xmflsct** [comment]
Yes that could be an approach as well! Guess the readme can be updated to prepare for their SDK 41 release.

**Comment by tomzaku** [comment]
Fixed and updated read me
