### ISSUE TITLE
Flickering with LayoutAnimation?

### ISSUE THREAD

**Issue by xmflsct** [tomzaku/react-native-shimmer-placeholder#56]
So I am using this library on a page. And a button on this page triggers a `LayoutAnimation` when tapped. The button's animation is fine, but when `LayoutAnimation` is triggered, all the components wrapped by this library flickers. Is there a reason why?

**Comment by tomzaku** [comment]
Can u send me a demo code?

**Comment by xmflsct** [comment]
I figure out now. Because of using shimmer placeholder, now my component renders before the remote data get fetched. And my data is passed through as a props which shimmer placeholder can check when to hide. In this case, props changes as it is a rerender, and `LayoutAnimation` makes rerender visible.
