### ISSUE TITLE
Shimmer crashes on expo SDK 41

### ISSUE THREAD

**Issue by Infinitism** [tomzaku/react-native-shimmer-placeholder#66]
Just importing and starting the component with <ShimmerPlaceholder /> breaks the app. It won't even render!

Using Expo SDK 41 with expo-linear-gradient.

**Comment by Infinitism** [comment]
This is an issue with how the globals are imported into the package. If using SDK 41, here is a work around!

`import {createShimmerPlaceholder} from 'react-native-shimmer-placeholder';
import { LinearGradient } from 'expo-linear-gradient';

const ShimmerPlaceHolder = createShimmerPlaceholder(LinearGradient)`

**Comment by Tsugami** [comment]
I'm suffering with the same problem, thanks for the solution @Infinitism

**Comment by tomzaku** [comment]
Fixed and updated readme
