### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by anangkf** [tomzaku/react-native-shimmer-placeholder#87]
Hi, I think the documentation should be updated. 
LinearGradient should be imported as named import instead of Default import.

so this one should be changed:
```import LinearGradient from 'expo-linear-gradient';```
to: 
```import { LinearGradient } from 'expo-linear-gradient';```

**Comment by sidpremkumar** [comment]
Thank you so much @anangkf , was about to give up and this saved me 🙇
